# Generated by Django 5.2.8 on 2025-11-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('peso', models.CharField(max_length=50)),
                ('sesiones', models.CharField(max_length=50)),
                ('activacion_muscular', models.CharField(max_length=50)),
                ('descripcion_de_la_ultima_sesion', models.CharField(max_length=50)),
                ('tamano_de_la_pantorrilla', models.CharField(max_length=50, null=True)),
                ('rol', models.CharField(choices=[('paciente', 'Paciente'), ('doctor', 'Doctor')], max_length=10)),
            ],
        ),
    ]
