# Generated by Django 5.2.8 on 2025-11-09 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_activacion_muscular_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='activacion_muscular',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='descripcion_de_la_ultima_sesion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='sesiones',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tamano_de_la_pantorrilla',
        ),
    ]
