# Generated by Django 5.2.8 on 2025-11-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
