# Generated by Django 5.2.8 on 2025-11-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_usuario_altura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
            ],
            options={
                'db_table': 'maquinas',
            },
        ),
    ]
