# Generated by Django 5.2.8 on 2025-11-19 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_maquinas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComandoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('iniciar', 'Iniciar'), ('detener', 'Detener'), ('pausar', 'Pausar'), ('continuar', 'Continuar')], max_length=20)),
                ('grados', models.IntegerField(blank=True, null=True)),
                ('repeticiones', models.IntegerField(blank=True, null=True)),
                ('ejecutado', models.BooleanField(default=False)),
                ('timestamp_creacion', models.FloatField(default=0)),
                ('timestamp_ejecucion', models.FloatField(blank=True, null=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandos', to='usuarios.maquinas')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comandos_maquinas',
                'ordering': ['timestamp_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EstadoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('grados_actuales', models.IntegerField(default=0)),
                ('repeticiones', models.IntegerField(default=0)),
                ('ultimo_timestamp', models.FloatField(default=0)),
                ('conectado', models.BooleanField(default=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('maquina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_actual', to='usuarios.maquinas')),
            ],
            options={
                'db_table': 'estado_maquinas',
            },
        ),
        migrations.CreateModel(
            name='SesionTerapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('grados_objetivo', models.IntegerField()),
                ('repeticiones_objetivo', models.IntegerField()),
                ('repeticiones_completadas', models.IntegerField(default=0)),
                ('completada', models.BooleanField(default=False)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='usuarios.maquinas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_terapia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sesiones_terapia',
            },
        ),
    ]
