# Generated by Django 5.2.4 on 2025-11-20 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_comandomaquina_estadomaquina_sesionterapia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadomaquina',
            name='fecha_actualizacion',
        ),
        migrations.AddField(
            model_name='estadomaquina',
            name='modo',
            field=models.CharField(default='normal', max_length=50),
        ),
        migrations.AddField(
            model_name='estadomaquina',
            name='stop_grados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadomaquina',
            name='conectado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='estadomaquina',
            name='maquina',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.maquinas'),
        ),
        migrations.AlterField(
            model_name='estadomaquina',
            name='ultimo_timestamp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='estadomaquina',
            table=None,
        ),
    ]
